[phases.setup]
nixPkgs = ["python311", "curl", "pkgconfig"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn shopify_api:app --host 0.0.0.0 --port $PORT"
